/**
 * @motebit/crypto-play-integrity — DEPRECATED.
 *
 * **Use `@motebit/crypto-android-keystore` instead** for canonical
 * sovereign-verifiable Android hardware attestation.
 *
 * ## Why this package was deprecated
 *
 * This package was scaffolded against a pinned-Google-JWKS model that
 * Google's Play Integrity API does not support. Google publishes no
 * global JWKS for Play Integrity verdict signing; the verification
 * public key is per-app, generated by Play Console for the developer,
 * exported as `base64_of_encoded_verification_key` to `local.properties`,
 * and never globally published — by deliberate design. Verification is
 * either (a) a network round-trip to `playintegrity.googleapis.com`
 * with the developer's service-account credentials, or (b) local
 * decryption with a key only the developer holds. Neither path
 * satisfies the motebit invariant of third-party verification against
 * publicly-pinned anchors.
 *
 * The architecturally-correct Android primitive — public-anchor,
 * third-party-verifiable, no per-deployer secrets — is **Android
 * Hardware-Backed Keystore Attestation**, shipped at
 * `@motebit/crypto-android-keystore` since 2026-04-26. That package
 * verifies device attestation chains against Google's published
 * Hardware Attestation roots (RSA + ECDSA P-384), the Android
 * equivalent of Apple's App Attest CA model. `@motebit/crypto-play-integrity`
 * survives published only for one minor cycle of dep-resolution
 * stability before being unpublished at `2.0.0`.
 *
 * ## What this package would still be good for
 *
 * Play Integrity remains a useful **operator-mode anti-fraud signal**
 * — Google's `playProtectVerdict`, `appAccessRiskVerdict`, and
 * `licensingVerdict` carry meaningful per-deployer risk data. But
 * those signals are not third-party verifiable cryptographic claims,
 * so they do not belong in the permissive-floor crypto-leaf set
 * alongside WebAuthn / App Attest / TPM / Android Keystore. If a
 * future motebit relay deployment wants Play Integrity-as-anti-fraud,
 * the right home is a relay-side service or an explicitly
 * non-canonical operator package — not this one.
 *
 * @deprecated since 1.1.0, removed in 2.0.0. Use `@motebit/crypto-android-keystore` for canonical Android hardware attestation instead.
 *
 * Reason: the entire pinned-Google-JWKS premise this package was scaffolded against does not match Google's Play Integrity API design — Google publishes no public JWKS for verdict signing; verification keys are per-app, generated by Play Console, never globally published. The architecturally-correct sovereign-verifiable Android primitive is Hardware-Backed Keystore Attestation, which chains to Google's published Hardware Attestation roots. See `docs/doctrine/hardware-attestation.md` § "Three architectural categories".
 */

import type { HardwareAttestationClaim } from "@motebit/protocol";

import type { GoogleJwks } from "./google-jwks.js";
import type { PlayIntegrityVerifyOptions, PlayIntegrityVerifyResult } from "./verify.js";
import { verifyPlayIntegrityToken } from "./verify.js";

// eslint-disable-next-line @typescript-eslint/no-deprecated -- the entire package is deprecated; re-exporting deprecated members from a deprecated index is the documented contract.
export { GOOGLE_PLAY_INTEGRITY_JWKS, type GoogleJwk, type GoogleJwks } from "./google-jwks.js";
export { decodeJwt, verifyJwtSignature } from "./jwt.js";
export type { DecodedJwt, JwtHeader, PlayIntegrityPayload } from "./jwt.js";
export { verifyPlayIntegrityToken } from "./verify.js";
export type {
  PlayIntegrityVerifyOptions,
  PlayIntegrityVerifyResult,
  PlayIntegrityVerifyError,
} from "./verify.js";

/**
 * Shape the optional verifier injected into `@motebit/crypto`'s
 * `HardwareAttestationVerifiers.playIntegrity` slot carries — mirrors
 * the sync-or-async return shape the dispatcher supports.
 */
export interface PlayIntegrityVerifyDispatchResult {
  readonly valid: boolean;
  readonly platform: "play_integrity";
  readonly errors: ReadonlyArray<{ readonly message: string }>;
  readonly attestation_detail?: PlayIntegrityVerifyResult;
}

/**
 * Context fields the dispatcher lifts out of the credential subject and
 * threads through to the verifier. All four participate in the JCS
 * body the Kotlin mint path hashes into the Play Integrity nonce, so
 * the verifier re-derives the body from them and byte-compares against
 * `payload.nonce` (see `verify.ts`, step 4).
 *
 * Each field optional: a caller that omits one loses the
 * identity-binding channel but still gets JWT-signature / package /
 * device-integrity results — the verifier reports the missing channel
 * explicitly rather than silently passing.
 */
export interface PlayIntegrityVerifierContext {
  readonly expectedMotebitId?: string;
  readonly expectedDeviceId?: string;
  readonly expectedAttestedAt?: number;
}

export interface PlayIntegrityVerifierConfig {
  /** Android package the Play Integrity verdict must bind to. */
  readonly expectedPackageName: string;
  /** Optional: override the pinned Google JWKS (tests fabricate their own). */
  readonly pinnedJwks?: GoogleJwks;
  /**
   * Optional: relax the device-integrity floor (e.g. for sideloaded dev
   * builds). Defaults to the strict `"MEETS_DEVICE_INTEGRITY"`.
   */
  readonly requiredDeviceIntegrity?: string;
}

/**
 * Factory — build a `playIntegrity` verifier bound to a specific
 * package and (optionally) a test JWKS / relaxed integrity floor. The
 * returned function matches the
 * `HardwareAttestationVerifiers.playIntegrity` signature the
 * `@motebit/crypto` dispatcher expects.
 *
 * @deprecated since 1.1.0, removed in 2.0.0. Use `androidKeystoreVerifier` from `@motebit/crypto-android-keystore` instead — the canonical sovereign-verifiable Android hardware attestation primitive.
 *
 *   Reason: the pinned-Google-JWKS model this factory was scaffolded
 *   against does not match Google's Play Integrity API design — Google
 *   publishes no public JWKS for Play Integrity verdicts; verification
 *   keys are per-app, generated by Play Console, never globally
 *   published. The structurally-correct sovereign-verifiable Android
 *   primitive is Hardware-Backed Keystore Attestation, which chains to
 *   Google's published Hardware Attestation roots. See
 *   `docs/doctrine/hardware-attestation.md` § "Three architectural
 *   categories".
 */
export function playIntegrityVerifier(
  config: PlayIntegrityVerifierConfig,
): (
  claim: HardwareAttestationClaim,
  expectedIdentityHex: string,
  context?: PlayIntegrityVerifierContext,
) => Promise<PlayIntegrityVerifyDispatchResult> {
  return async (claim, expectedIdentityHex, context) => {
    const opts: PlayIntegrityVerifyOptions = {
      expectedPackageName: config.expectedPackageName,
      expectedIdentityPublicKeyHex: expectedIdentityHex,
      ...(config.pinnedJwks !== undefined ? { pinnedJwks: config.pinnedJwks } : {}),
      ...(config.requiredDeviceIntegrity !== undefined
        ? { requiredDeviceIntegrity: config.requiredDeviceIntegrity }
        : {}),
      ...(context?.expectedMotebitId !== undefined
        ? { expectedMotebitId: context.expectedMotebitId }
        : {}),
      ...(context?.expectedDeviceId !== undefined
        ? { expectedDeviceId: context.expectedDeviceId }
        : {}),
      ...(context?.expectedAttestedAt !== undefined
        ? { expectedAttestedAt: context.expectedAttestedAt }
        : {}),
    };
    const detail = await verifyPlayIntegrityToken(claim, opts);
    return {
      valid: detail.valid,
      platform: "play_integrity",
      errors: detail.errors,
      attestation_detail: detail,
    };
  };
}
