/**
 * Commitment-bond wire schema — the agent's anti-sybil staked signal.
 *
 * `BondCommitment` is a self-signed proof-of-funds at the agent's OWN sovereign
 * Solana address — `bonded_address` MUST equal `base58btc(bonded_public_key)`
 * (enforced by `@motebit/crypto`'s `verifyBondCommitment`, locked by
 * `check-bond-address-binding`). Phase 1 is a SIGNAL, not collateral / escrow /
 * recourse. Signs under `motebit-jcs-ed25519-b64-v1` (b64url).
 *
 * See `spec/bond-v1.md` and `docs/doctrine/commitment-bond.md`.
 */

import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

import type { BondCommitment, SettlementAsset } from "@motebit/protocol";
import { ALL_SETTLEMENT_ASSETS } from "@motebit/protocol";

import { assembleJsonSchemaFor } from "./assemble.js";
import type { ParityForward, ParityReverse } from "./__parity/check.js";

// ---------------------------------------------------------------------------
// Stable $id URL
// ---------------------------------------------------------------------------

export const BOND_COMMITMENT_SCHEMA_ID =
  "https://raw.githubusercontent.com/motebit/motebit/main/spec/schemas/bond-commitment-v1.json";

// ---------------------------------------------------------------------------
// BondCommitment
// ---------------------------------------------------------------------------

export const BondCommitmentSchema = z
  .object({
    bond_id: z.string().min(1).describe("UUID v7, generated by the bonding agent."),
    motebit_id: z.string().min(1).describe("MotebitId of the bonding agent."),
    bonded_public_key: z
      .string()
      .regex(/^[0-9a-f]{64}$/, "bonded_public_key MUST be 64 lowercase hex characters")
      .describe(
        "Hex-encoded 32-byte Ed25519 identity public key — the signer, whose base58btc encoding IS `bonded_address`.",
      ),
    bonded_address: z
      .string()
      .min(1)
      .describe(
        "Base58 sovereign address holding the backing capital. MUST equal base58btc(bonded_public_key) — the anti-sybil binding a verifier re-checks fail-closed.",
      ),
    bond_amount_micro: z
      .number()
      .int()
      .nonnegative()
      .describe("Committed amount in integer USDC micro-units (1 USD = 1,000,000)."),
    asset: z
      // Cast preserves the literal `SettlementAsset` union in z.infer (same A5
      // pattern as settlement-record's settlement_mode). Runtime validation is
      // identical — z.enum checks against the same ALL_SETTLEMENT_ASSETS values.
      .enum(ALL_SETTLEMENT_ASSETS as unknown as [SettlementAsset, ...SettlementAsset[]])
      .describe("The settlement asset backing the bond. `USDC` at land."),
    chain: z
      .string()
      .min(1)
      .describe(
        "CAIP-2 chain identifier the bonded_address lives on (e.g. solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp).",
      ),
    issued_at: z.number().describe("Epoch milliseconds when the bond was issued."),
    expires_at: z
      .number()
      .describe("Epoch milliseconds when the bond commitment expires and must be re-issued."),
    suite: z
      .literal("motebit-jcs-ed25519-b64-v1")
      .describe(
        "Cryptosuite — always `motebit-jcs-ed25519-b64-v1` (JCS, Ed25519, base64url signature). Verifiers reject missing or unknown values fail-closed.",
      ),
    signature: z
      .string()
      .min(1)
      .describe(
        "Base64url Ed25519 signature over canonicalJson of every field except `signature`, by `bonded_public_key`.",
      ),
  })
  .strict();

type _InferredBond = z.infer<typeof BondCommitmentSchema>;
type _BondForward = ParityForward<BondCommitment, _InferredBond>;
type _BondReverse = ParityReverse<BondCommitment, _InferredBond>;

export const _BOND_COMMITMENT_TYPE_PARITY: {
  forward: _BondForward;
  reverse: _BondReverse;
} = {
  forward: true,
  reverse: true,
};

export function buildBondCommitmentJsonSchema(): Record<string, unknown> {
  const raw = zodToJsonSchema(BondCommitmentSchema, {
    name: "BondCommitment",
    $refStrategy: "root",
    target: "jsonSchema7",
  }) as Record<string, unknown>;
  return assembleJsonSchemaFor("BondCommitment", raw, {
    $id: BOND_COMMITMENT_SCHEMA_ID,
    title: "BondCommitment (v1)",
    description:
      "An agent's self-signed commitment bond — proof-of-funds at its OWN sovereign Solana address (bonded_address == base58btc(bonded_public_key)). An anti-sybil staked signal, RPC-verified never custodied; phase 1 is a signal, NOT collateral/escrow/recourse. See spec/bond-v1.md.",
  });
}
