/**
 * Dispute types — motebit/dispute@1.0.
 *
 * MIT: these types define the interoperable format for dispute resolution
 * in agent-to-agent delegations. Any implementation can produce and verify
 * dispute artifacts using these types.
 */

// === Dispute Lifecycle (§3) ===

/** Dispute lifecycle states. Terminal states (final, expired) are irreversible. */
export type DisputeState =
  | "opened"
  | "evidence"
  | "arbitration"
  | "resolved"
  | "appealed"
  | "final"
  | "expired";

/** Dispute resolution outcome. */
export type DisputeOutcome = "upheld" | "overturned" | "split";

/** Dispute category (§4.2). */
export type DisputeCategory =
  | "quality"
  | "non_payment"
  | "receipt_invalid"
  | "unauthorized"
  | "other";

/** Fund action resulting from dispute resolution (§7.2). */
export type DisputeFundAction = "release_to_worker" | "refund_to_delegator" | "split";

// === Dispute Initiation (§4) ===

/**
 * Request to open a dispute on a completed task.
 *
 * Foundation Law (§4.4):
 * - task_id and allocation_id are required — no economic binding, no dispute
 * - Filing party must be a direct party to the referenced task
 * - At least one evidence reference is required at filing time
 * - A relay must not reject an eligible dispute
 */
export interface DisputeRequest {
  /** UUID v7, generated by filing party. */
  dispute_id: string;
  /** Must reference an existing task. */
  task_id: string;
  /** Must reference the task's BudgetAllocation. */
  allocation_id: string;
  /** MotebitId of the filing party. */
  filed_by: string;
  /** MotebitId of the other task party. */
  respondent: string;
  /** Dispute category. */
  category: DisputeCategory;
  /** Human-readable explanation. */
  description: string;
  /** At least one reference to a signed artifact. */
  evidence_refs: string[];
  /** Unix ms. */
  filed_at: number;
  /**
   * Cryptosuite discriminator. Always `"motebit-jcs-ed25519-b64-v1"` —
   * JCS canonicalization, Ed25519 primitive, base64url signature
   * encoding. Verifiers reject missing or unknown values fail-closed.
   */
  suite: "motebit-jcs-ed25519-b64-v1";
  /** Ed25519 over canonical JSON of all fields except signature. */
  signature: string;
}

// === Evidence (§5) ===

/** Evidence types that can be submitted in a dispute (§5.1). */
export type DisputeEvidenceType =
  | "execution_receipt"
  | "credential"
  | "anchor_proof"
  | "settlement_proof"
  | "execution_ledger"
  | "attestation";

/**
 * Evidence submitted in a dispute.
 *
 * Foundation Law (§5.4):
 * - Evidence must be cryptographically verifiable
 * - Both parties must have equal access to the evidence window
 * - The relay must not tamper with or withhold submitted evidence
 */
export interface DisputeEvidence {
  /** Must reference an open dispute. */
  dispute_id: string;
  /** MotebitId of the submitting party. */
  submitted_by: string;
  /** Evidence type. */
  evidence_type: DisputeEvidenceType;
  /** The signed artifact itself. */
  evidence_data: Record<string, unknown>;
  /** What this evidence demonstrates. */
  description: string;
  /** Unix ms. */
  submitted_at: number;
  /**
   * Cryptosuite discriminator. Always `"motebit-jcs-ed25519-b64-v1"`
   * (see DisputeRequest for the full recipe).
   */
  suite: "motebit-jcs-ed25519-b64-v1";
  /** Ed25519 over canonical JSON of all fields except signature. */
  signature: string;
}

// === Adjudication (§6) ===

/**
 * Individual vote by a federation peer in federation adjudication (§6.2).
 *
 * Foundation Law (§6.5):
 * - Federation resolution must include individual AdjudicatorVote entries
 * - Aggregated-only verdicts are rejected
 */
export interface AdjudicatorVote {
  /** Federation peer MotebitId. */
  peer_id: string;
  /** Vote outcome. */
  vote: DisputeOutcome;
  /** Per-peer explanation. */
  rationale: string;
  /**
   * Cryptosuite discriminator. Always `"motebit-jcs-ed25519-b64-v1"`
   * (see DisputeRequest for the full recipe).
   */
  suite: "motebit-jcs-ed25519-b64-v1";
  /** Ed25519 by the voting peer. */
  signature: string;
}

/**
 * Dispute resolution by adjudicator.
 *
 * Foundation Law (§6.5):
 * - Resolution must include a signed rationale
 * - A relay must not self-adjudicate when it is the defendant
 */
export interface DisputeResolution {
  /** Must reference the dispute. */
  dispute_id: string;
  /** Resolution outcome. */
  resolution: DisputeOutcome;
  /** Signed explanation of the decision. */
  rationale: string;
  /** How funds are distributed. */
  fund_action: DisputeFundAction;
  /** [0, 1], worker's portion. 1.0 = all to worker. */
  split_ratio: number;
  /** MotebitId or relay ID of the adjudicating entity. */
  adjudicator: string;
  /** For federation — empty for single-relay. */
  adjudicator_votes: AdjudicatorVote[];
  /** Unix ms. */
  resolved_at: number;
  /**
   * Cryptosuite discriminator. Always `"motebit-jcs-ed25519-b64-v1"`
   * (see DisputeRequest for the full recipe).
   */
  suite: "motebit-jcs-ed25519-b64-v1";
  /** Ed25519 over canonical JSON of all fields except signature. */
  signature: string;
}

// === Appeal (§8) ===

/**
 * Appeal filed against a dispute resolution.
 *
 * Foundation Law (§8.4):
 * - One appeal per dispute — final state after appeal is terminal
 * - New evidence may be submitted with the appeal
 */
export interface DisputeAppeal {
  /** Must reference a resolved dispute. */
  dispute_id: string;
  /** MotebitId of the appealing party. */
  appealed_by: string;
  /** Why the resolution is incorrect. */
  reason: string;
  /** Optional: new evidence references. */
  additional_evidence?: string[];
  /** Unix ms. */
  appealed_at: number;
  /**
   * Cryptosuite discriminator. Always `"motebit-jcs-ed25519-b64-v1"`
   * (see DisputeRequest for the full recipe).
   */
  suite: "motebit-jcs-ed25519-b64-v1";
  /** Ed25519 over canonical JSON of all fields except signature. */
  signature: string;
}
