/**
 * check-api-surface — the gate must see a break even after its author ran
 * `api:extract` and committed the regenerated baseline (the bypass its own
 * resolution text used to invite), and must offer the right bump for an
 * additive change instead of only "major or revert".
 *
 * SAFETY (#835): every git command in this file runs through `fxGit`, with
 * EVERY `GIT_*` variable removed, GIT_CEILING_DIRECTORIES set to the test's
 * temp dir, and a pre-flight assertion that the repository git would act on
 * lives inside that temp dir. A pre-push hook in a linked worktree exports
 * GIT_DIR; without this the fixture would rewrite the real repository.
 */
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, join, relative } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

import {
  checkBaselineHistory,
  classifyBaselineChange,
  pendingBumps,
  scrubGitEnv,
} from "../lib/api-baseline-history.js";
import { runApiSurfaceGate, type TrackedPackage } from "../check-api-surface.js";

function inside(parent: string, child: string): boolean {
  const rel = relative(realpathSync(parent), child);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function fxGit(jail: string, args: string[]): string {
  const env = {
    ...scrubGitEnv(process.env),
    GIT_CEILING_DIRECTORIES: realpathSync(jail),
    GIT_AUTHOR_NAME: "fixture",
    GIT_AUTHOR_EMAIL: "fixture@example.invalid",
    GIT_COMMITTER_NAME: "fixture",
    GIT_COMMITTER_EMAIL: "fixture@example.invalid",
  };
  if (args[0] !== "init" && args[0] !== "clone") {
    const probe = spawnSync("git", ["rev-parse", "--absolute-git-dir"], {
      cwd: jail,
      env,
      encoding: "utf8",
    });
    const gitDir = probe.status === 0 ? probe.stdout.trim() : null;
    if (gitDir === null || !inside(jail, gitDir)) {
      throw new Error(`fxGit: refusing \`git ${args.join(" ")}\` outside ${jail} (${gitDir})`);
    }
  }
  const r = spawnSync(
    "git",
    ["-c", "commit.gpgsign=false", "-c", "maintenance.auto=false", ...args],
    {
      cwd: jail,
      env,
      encoding: "utf8",
    },
  );
  if (r.status !== 0) throw new Error(`git ${args.join(" ")} failed:\n${r.stderr}`);
  return r.stdout;
}

const BASELINE = `## API Report File for "@fx/crypto"

> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).

\`\`\`ts

// @public
export type VerifyResult = IdentityVerifyResult | ReceiptVerifyResult | UnknownVerifyResult;

// @public (undocumented)
export interface ReceiptVerifyResult {
    // (undocumented)
    readonly kind: "receipt";
    // (undocumented)
    readonly valid: boolean;
}

// @public (undocumented)
export interface IdentityVerifyResult {
    // (undocumented)
    readonly kind: "identity";
}

// @public
export function verify(input: string): Promise<VerifyResult>;

\`\`\`
`;

const REMOVAL = BASELINE.replace(" | UnknownVerifyResult;", ";");
/** An added optional member: source-compatible for most callers, breaking by the conservative rule. */
const OPTIONAL_MEMBER = BASELINE.replace(
  "    readonly valid: boolean;\n",
  "    readonly valid: boolean;\n    // (undocumented)\n    readonly reason?: string;\n",
);
/** An entirely new top-level export: the only additive shape. */
const ADDITIVE = BASELINE.replace(
  "// @public\nexport function verify(",
  "// @public\nexport function verifyAll(inputs: string[]): Promise<VerifyResult[]>;\n\n// @public\nexport function verify(",
);

describe("classifyBaselineChange", () => {
  it("a narrowed union is breaking", () => {
    const c = classifyBaselineChange(BASELINE, REMOVAL);
    expect(c.kind).toBe("breaking");
    expect(c.changed).toEqual([
      "export type VerifyResult = IdentityVerifyResult | ReceiptVerifyResult | UnknownVerifyResult;",
    ]);
  });

  it("an added optional member of an existing interface is breaking (conservative rule)", () => {
    const c = classifyBaselineChange(BASELINE, OPTIONAL_MEMBER);
    expect(c.kind).toBe("breaking");
    expect(c.changed).toEqual(["export interface ReceiptVerifyResult {"]);
  });

  it("a new top-level export is additive", () => {
    const c = classifyBaselineChange(BASELINE, ADDITIVE);
    expect(c.kind).toBe("additive");
    expect(c.added).toEqual([
      "export function verifyAll(inputs: string[]): Promise<VerifyResult[]>;",
    ]);
  });

  it("a removed top-level declaration is breaking", () => {
    const removed = BASELINE.replace(
      "// @public\nexport function verify(input: string): Promise<VerifyResult>;\n",
      "",
    );
    const c = classifyBaselineChange(BASELINE, removed);
    expect(c.kind).toBe("breaking");
    expect(c.removed).toEqual(["export function verify(input: string): Promise<VerifyResult>;"]);
  });

  it("comment-only and blank-only changes are unchanged; reordering members is breaking", () => {
    const commented = BASELINE.replace("// @public\nexport function", "// @beta\nexport function");
    expect(classifyBaselineChange(BASELINE, commented).kind).toBe("unchanged");
    expect(classifyBaselineChange(BASELINE, `${BASELINE}\n\n`).kind).toBe("unchanged");
    const reordered = BASELINE.replace(
      '    // (undocumented)\n    readonly kind: "receipt";\n    // (undocumented)\n    readonly valid: boolean;\n',
      '    // (undocumented)\n    readonly valid: boolean;\n    // (undocumented)\n    readonly kind: "receipt";\n',
    );
    expect(reordered).not.toBe(BASELINE);
    expect(classifyBaselineChange(BASELINE, reordered).kind).toBe("breaking");
  });

  it("an added column-0 line inside an open declaration never passes as a new export", () => {
    const sneaky = BASELINE.replace(
      '    readonly kind: "identity";\n',
      '    readonly kind: "identity";\nexport declare const extra: string;\n',
    );
    expect(classifyBaselineChange(BASELINE, sneaky).kind).toBe("breaking");
  });

  it("moving a member to another declaration is breaking, not reordering", () => {
    const moved = BASELINE.replace(
      "    // (undocumented)\n    readonly valid: boolean;\n",
      "",
    ).replace(
      '    readonly kind: "identity";\n',
      '    readonly kind: "identity";\n    readonly valid: boolean;\n',
    );
    const c = classifyBaselineChange(BASELINE, moved);
    expect(c.kind).toBe("breaking");
    expect(c.changed).toEqual([
      "export interface ReceiptVerifyResult {",
      "export interface IdentityVerifyResult {",
    ]);
  });

  it("no baseline at the merge-base is a newly tracked package", () => {
    expect(classifyBaselineChange(null, BASELINE).kind).toBe("new");
  });
});

/**
 * The verifier's probes against the history classifier. The rule is SOUND by
 * over-approximation: only an entirely new top-level declaration is additive;
 * any change inside an existing one (union variants and members included,
 * optional or required) is breaking; comment/blank edits and reordering whole
 * declarations are no change.
 */
const UNION_BASELINE = `## API Report File for "@fx/crypto"

> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).

\`\`\`ts

// @public
export type Outcome = {
    kind: "ok";
    value: string;
} | {
    kind: "err";
    error: string;
} | {
    kind: "pending";
    retry_at: number;
};

// @public
export interface VerifyOptions {
    // (undocumented)
    strict?: boolean;
}

// @public
export function verify(input: string, options?: VerifyOptions): Outcome;

\`\`\`
`;

describe("classifyBaselineChange — verifier probes", () => {
  it("swapping kind tags between non-first union variants is breaking", () => {
    const swapped = UNION_BASELINE.replace('kind: "err";', 'kind: "@@";')
      .replace('kind: "pending";', 'kind: "err";')
      .replace('kind: "@@";', 'kind: "pending";');
    expect(swapped).not.toBe(UNION_BASELINE);
    expect(classifyBaselineChange(UNION_BASELINE, swapped).kind).toBe("breaking");
  });

  it("moving a field between union variants is breaking", () => {
    const moved = UNION_BASELINE.replace("    error: string;\n", "").replace(
      "    retry_at: number;\n",
      "    retry_at: number;\n    error: string;\n",
    );
    expect(classifyBaselineChange(UNION_BASELINE, moved).kind).toBe("breaking");
  });

  it("an added REQUIRED member of an existing declaration is breaking", () => {
    const required = UNION_BASELINE.replace(
      "    strict?: boolean;\n",
      "    strict?: boolean;\n    nonce: string;\n",
    );
    const c = classifyBaselineChange(UNION_BASELINE, required);
    expect(c.kind).toBe("breaking");
    expect(c.changed).toEqual(["export interface VerifyOptions {"]);
  });

  it("an added OPTIONAL member of an existing declaration is breaking (conservative rule)", () => {
    const optional = UNION_BASELINE.replace(
      "    strict?: boolean;\n",
      "    strict?: boolean;\n    // (undocumented)\n    nonce?: string;\n",
    );
    expect(classifyBaselineChange(UNION_BASELINE, optional).kind).toBe("breaking");
  });

  it("a new top-level export is additive", () => {
    const added = UNION_BASELINE.replace(
      "// @public\nexport function verify",
      "// @public\nexport function verifyAll(inputs: string[]): Outcome[];\n\n// @public\nexport function verify",
    );
    const c = classifyBaselineChange(UNION_BASELINE, added);
    expect(c.kind).toBe("additive");
    expect(c.added).toEqual(["export function verifyAll(inputs: string[]): Outcome[];"]);
    expect(c.removed).toEqual([]);
    expect(c.changed).toEqual([]);
  });

  it("comment-only edits are no change", () => {
    const commented = UNION_BASELINE.replace(
      "    // (undocumented)\n    strict?: boolean;\n",
      "    // Reject unknown fields.\n    strict?: boolean;\n",
    ).replace("// @public\nexport function", "// @beta\nexport function");
    expect(commented).not.toBe(UNION_BASELINE);
    expect(classifyBaselineChange(UNION_BASELINE, commented).kind).toBe("unchanged");
  });

  it("the report's import header is not surface; a new export using a new import is additive", () => {
    const withImport = UNION_BASELINE.replace(
      "```ts\n\n",
      "```ts\n\nimport type { Nonce } from '@fx/protocol';\n\n",
    ).replace(
      "// @public\nexport function verify",
      "// @public\nexport function mint(n: Nonce): string;\n\n// @public\nexport function verify",
    );
    expect(classifyBaselineChange(UNION_BASELINE, withImport).kind).toBe("additive");
  });

  it("reordering whole top-level declarations is no change", () => {
    const fn =
      "// @public\nexport function verify(input: string, options?: VerifyOptions): Outcome;\n\n";
    const reordered = UNION_BASELINE.replace(fn, "").replace("```ts\n\n", `\`\`\`ts\n\n${fn}`);
    expect(reordered).not.toBe(UNION_BASELINE);
    expect(classifyBaselineChange(UNION_BASELINE, reordered).kind).toBe("unchanged");
  });
});

describe("fixture repository", () => {
  let jail: string;

  const write = (rel: string, content: string) => {
    const abs = join(jail, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  };
  const commit = (msg: string) => {
    fxGit(jail, ["add", "-A"]);
    fxGit(jail, ["commit", "-q", "-m", msg]);
  };
  const changeset = (name: string, bump: string) =>
    write(`.changeset/${name}.md`, `---\n"@fx/crypto": ${bump}\n---\n\nFixture.\n`);

  const TRACKED_FX: TrackedPackage[] = [
    { path: "packages/crypto", name: "@fx/crypto", baseline: "etc/crypto.api.md" },
  ];
  const BASELINE_PATH = "packages/crypto/etc/crypto.api.md";

  /** The gate with the extractor reporting "built surface matches the committed baseline". */
  const gate = (extracted?: string) => {
    let out = "";
    const code = runApiSurfaceGate({
      root: jail,
      tracked: TRACKED_FX,
      baseRef: "origin/main",
      extract: () =>
        extracted === undefined
          ? { ok: true, output: "" }
          : { ok: false, output: "Warning: You have changed the API signature\n", extracted },
      write: (t) => {
        out += t;
      },
    });
    return { code, out };
  };

  beforeEach(() => {
    jail = realpathSync(mkdtempSync(join(tmpdir(), "api-surface-fx-")));
    fxGit(jail, ["init", "-q", "-b", "main"]);
    write(".changeset/README.md", "# Changesets\n");
    write(BASELINE_PATH, BASELINE);
    commit("main");
    // A local stand-in for the fetched base branch.
    fxGit(jail, ["update-ref", "refs/remotes/origin/main", "HEAD"]);
    fxGit(jail, ["checkout", "-q", "-b", "feature"]);
  });

  afterEach(() => {
    rmSync(jail, { recursive: true, force: true });
  });

  it("(1) a regenerated, committed baseline that removes a declaration fails with no changeset", () => {
    write(BASELINE_PATH, REMOVAL);
    commit("break + regenerate baseline");
    const { code, out } = gate();
    expect(code).toBe(1);
    expect(out).toContain("BREAKING change needs a pending `major` changeset (declared: none)");
    expect(out).toContain("| UnknownVerifyResult;");
  });

  it("(1) a minor changeset does not cover a regenerated breaking baseline; a major does", () => {
    write(BASELINE_PATH, REMOVAL);
    changeset("minor-only", "minor");
    commit("break + minor");
    expect(gate().code).toBe(1);
    changeset("now-major", "major");
    commit("declare major");
    const { code, out } = gate();
    expect(code).toBe(0);
    expect(out).toContain("breaking change covered by pending `major` changeset");
  });

  it("(2) an additive stale baseline is offered the minor path, not only major-or-revert", () => {
    const { code, out } = gate(ADDITIVE);
    expect(code).toBe(1);
    expect(out).toContain("The change is ADDITIVE");
    expect(out).toContain('"@fx/crypto": minor (or higher)');
    expect(out).not.toContain("Accidental → revert");
  });

  it("an added optional member is offered major-or-revert, with the conservative rule named", () => {
    const { code, out } = gate(OPTIONAL_MEMBER);
    expect(code).toBe(1);
    expect(out).toContain("The change is BREAKING");
    expect(out).toContain("including an added optional field");
    expect(out).toContain("post-freeze follow-up");
  });

  it("a committed added optional member needs a major changeset; a minor does not cover it", () => {
    write(BASELINE_PATH, OPTIONAL_MEMBER);
    changeset("add-reason", "minor");
    commit("optional member + minor");
    const red = gate();
    expect(red.code).toBe(1);
    expect(red.out).toContain(
      "BREAKING change needs a pending `major` changeset (declared: `minor`)",
    );
    changeset("add-reason-major", "major");
    commit("declare major");
    expect(gate().code).toBe(0);
  });

  it("(2) an additive committed baseline needs a minor changeset and passes with one", () => {
    write(BASELINE_PATH, ADDITIVE);
    commit("additive + regenerate");
    const red = gate();
    expect(red.code).toBe(1);
    expect(red.out).toContain("ADDITIVE change needs a pending `minor` changeset");
    changeset("add-reason", "minor");
    commit("declare minor");
    expect(gate().code).toBe(0);
  });

  it("a breaking stale baseline keeps the major-or-revert resolution", () => {
    const { code, out } = gate(REMOVAL);
    expect(code).toBe(1);
    expect(out).toContain("The change is BREAKING");
    expect(out).toContain("Accidental → revert the API change");
  });

  it("an unchanged baseline needs no changeset", () => {
    expect(gate().code).toBe(0);
  });

  it("only this branch's baseline changes count — main moving on does not", () => {
    fxGit(jail, ["checkout", "-q", "main"]);
    write(BASELINE_PATH, REMOVAL);
    changeset("main-major", "major");
    commit("main's own released break");
    fxGit(jail, ["rm", "-q", ".changeset/main-major.md"]);
    commit("release consumed the changeset");
    fxGit(jail, ["update-ref", "refs/remotes/origin/main", "HEAD"]);
    fxGit(jail, ["checkout", "-q", "feature"]);
    fxGit(jail, ["merge", "-q", "--no-edit", "main"]);
    expect(gate().code).toBe(0);
  });

  it("fails closed with a repair instruction when the base ref is missing", () => {
    fxGit(jail, ["update-ref", "-d", "refs/remotes/origin/main"]);
    const { code, out } = gate();
    expect(code).toBe(1);
    expect(out).toContain("history NOT checked");
    expect(out).toContain("git fetch origin main");
  });

  it("fails closed with a repair instruction in a shallow clone without the merge-base", () => {
    write(BASELINE_PATH, REMOVAL);
    commit("feature 1");
    write("x.txt", "x");
    commit("feature 2");
    const clone = join(jail, "shallow");
    fxGit(jail, ["clone", "-q", "--depth", "1", "--branch", "feature", `file://${jail}`, clone]);
    // origin/main in the clone points at a commit the shallow history does not reach.
    const mainSha = fxGit(jail, ["rev-parse", "main"]).trim();
    const shallowGate = () => {
      fxGit(clone, ["fetch", "-q", "--depth", "1", "origin", "main:refs/remotes/origin/main"]);
      let out = "";
      const code = runApiSurfaceGate({
        root: clone,
        tracked: TRACKED_FX,
        baseRef: "origin/main",
        extract: () => ({ ok: true, output: "" }),
        write: (t) => {
          out += t;
        },
      });
      return { code, out };
    };
    expect(mainSha).toMatch(/^[0-9a-f]{40}/);
    const { code, out } = shallowGate();
    expect(code).toBe(1);
    expect(out).toContain("shallow clone");
    expect(out).toContain("git fetch --unshallow");
  });

  it("reads the fixture, never a repository named by inherited GIT_* variables", () => {
    const decoy = realpathSync(mkdtempSync(join(tmpdir(), "api-surface-decoy-")));
    try {
      fxGit(decoy, ["init", "-q", "-b", "main"]);
      writeFileSync(join(decoy, "d.txt"), "decoy");
      fxGit(decoy, ["add", "-A"]);
      fxGit(decoy, ["commit", "-q", "-m", "decoy"]);
      const before = readFileSync(join(decoy, ".git", "HEAD"), "utf8");
      write(BASELINE_PATH, REMOVAL);
      commit("break");
      const saved = { GIT_DIR: process.env.GIT_DIR, GIT_WORK_TREE: process.env.GIT_WORK_TREE };
      process.env.GIT_DIR = join(decoy, ".git");
      process.env.GIT_WORK_TREE = decoy;
      try {
        const result = checkBaselineHistory({
          root: jail,
          baseRef: "origin/main",
          packages: [{ name: "@fx/crypto", baselinePath: BASELINE_PATH }],
        });
        expect(result.ok).toBe(true);
        if (result.ok) expect(result.verdicts[0]!.change.kind).toBe("breaking");
      } finally {
        for (const [k, v] of Object.entries(saved)) {
          if (v === undefined) delete process.env[k];
          else process.env[k] = v;
        }
      }
      expect(readFileSync(join(decoy, ".git", "HEAD"), "utf8")).toBe(before);
    } finally {
      rmSync(decoy, { recursive: true, force: true });
    }
  });
});

describe("pendingBumps", () => {
  it("takes the highest bump per package across changesets", () => {
    const dir = mkdtempSync(join(tmpdir(), "api-surface-cs-"));
    try {
      writeFileSync(join(dir, "README.md"), '---\n"@a/x": major\n---\n');
      writeFileSync(join(dir, "one.md"), '---\n"@a/x": minor\n"@a/y": patch\n---\n\nx\n');
      writeFileSync(join(dir, "two.md"), "---\n'@a/y': major\n---\n\ny\n");
      const bumps = pendingBumps(dir);
      expect(bumps.get("@a/x")).toBe("minor");
      expect(bumps.get("@a/y")).toBe("major");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
