/**
 * `motebit.yaml` JSON Schema builder.
 *
 * Derives a JSON Schema (draft-07) from `MotebitYamlObjectSchema` — the
 * same zod object the `motebit up` parser, the LSP, and the drift-defense
 * for `.describe()` hover text all read. That closes the loop: one zod
 * schema, four consumers (parser, LSP, build-schema script, `motebit
 * schema` subcommand), zero duplication.
 *
 * Why publish it as a JSON Schema file at all? Two reasons:
 *
 *   1. **Third-party validation without the CLI.** VS Code's Red Hat
 *      YAML extension is the de-facto standard for YAML validation —
 *      it ships with every major Node/Python/Docker workspace. Pointing
 *      it at our committed `motebit-yaml-v1.json` gives motebit.yaml
 *      the same red-squiggle experience our LSP gives, on machines
 *      where `motebit lsp` was never installed.
 *
 *   2. **Protocol surface, not CLI-internal.** motebit.yaml is the
 *      declarative face of a sovereign identity. An external tool —
 *      a CI action, a dashboard, a third-party relay — should be
 *      able to parse and validate it without depending on our BSL
 *      runtime. A committed JSON Schema is that contract.
 *
 * The committed file at `schema/motebit-yaml-v1.json` is generated by
 * `scripts/build-schema.ts` and pinned by the drift test in
 * `__tests__/yaml-json-schema.test.ts`.
 */

import { zodToJsonSchema } from "zod-to-json-schema";

import { MotebitYamlObjectSchema } from "./yaml-config.js";

/** Stable `$id` for the motebit.yaml v1 schema. External tools pin to this. */
export const MOTEBIT_YAML_SCHEMA_ID =
  "https://raw.githubusercontent.com/motebit/motebit/main/apps/cli/schema/motebit-yaml-v1.json";

/**
 * Build the JSON Schema object. Pure — no filesystem, no network.
 * Called from the build script, the `motebit schema` subcommand, and
 * the drift test.
 */
export function buildYamlJsonSchema(): Record<string, unknown> {
  const schema = zodToJsonSchema(MotebitYamlObjectSchema, {
    name: "MotebitYaml",
    $refStrategy: "none",
    target: "jsonSchema7",
  }) as Record<string, unknown>;
  // zod-to-json-schema wraps the root in a `definitions.MotebitYaml` +
  // `$ref` envelope. External tools work better with a self-contained
  // top-level object, so unwrap.
  const definitions = schema["definitions"] as Record<string, Record<string, unknown>> | undefined;
  const root = definitions?.["MotebitYaml"] ?? schema;
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    $id: MOTEBIT_YAML_SCHEMA_ID,
    title: "motebit.yaml (v1)",
    description:
      "Declarative surface for a motebit: personality, provider, governance, MCP servers, and scheduled routines. Applied by `motebit up`.",
    ...root,
  };
}
