/**
 * #890 tamper checks — each fix, reverted, must turn its test red.
 *
 * Every entry is (file, text the fix added, what to put back, the test that
 * must go red). The runner applies one tamper at a time, rebuilds the
 * package when a downstream test reads its `dist`, runs the named test,
 * expects a FAILURE, and restores the file. An entry whose text is not found
 * is a failure of this script (a stale tamper would otherwise pass silently).
 *
 *   npx tsx scripts/tampers/890-goal-undetermined-refire.ts
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

interface Tamper {
  name: string;
  file: string;
  find: string;
  replace: string;
  /** Packages whose `dist` a downstream test reads — rebuilt before the run. */
  rebuild?: string[];
  /** Package dir the test runs in, and the test file. */
  pkg: string;
  test: string;
  /** Further edits applied with this one (a layered fix whose layers cover each other). */
  also?: Array<{ file: string; find: string; replace: string }>;
}

const TAMPERS: Tamper[] = [
  {
    name: "planner: an undetermined delegation fails its step instead of holding it",
    file: "packages/planner/src/plan-engine.ts",
    find: "            if (isDelegationUndetermined(err)) {",
    replace: "            if (false as boolean) {",
    pkg: "packages/planner",
    test: "src/__tests__/undetermined-refire-harness.test.ts",
  },
  {
    name: "planner: resume re-runs a held delegated step instead of settling it",
    file: "packages/planner/src/plan-engine.ts",
    find: "        if (step.status === StepStatus.Running && this.isDelegatedStep(step)) {\n          const settled",
    replace: "        if (false as boolean) {\n          const settled",
    pkg: "packages/planner",
    test: "src/__tests__/undetermined-refire-harness.test.ts",
  },
  {
    name: "planner: createPlan makes a new plan while the goal holds an undetermined step",
    file: "packages/planner/src/plan-engine.ts",
    find: "    if (held != null) {\n      throw new DelegationUndeterminedError",
    replace: "    if (held == null && held != null) {\n      throw new DelegationUndeterminedError",
    pkg: "packages/planner",
    test: "src/__tests__/undetermined-refire-harness.test.ts",
  },
  {
    name: "planner: sovereign 'payment status unknown' is not flagged undetermined",
    file: "packages/planner/src/sovereign-delegation-adapter.ts",
    find: "  err.undetermined = true;\n  return err;",
    replace: "  return err;",
    pkg: "packages/planner",
    test: "src/__tests__/sovereign-exactly-once.test.ts",
  },
  {
    name: "planner: InMemoryPlanStore.getPlanForGoal returns the first plan, not the latest",
    file: "packages/planner/src/types.ts",
    find: "if (latest == null || plan.created_at >= latest.created_at) latest = plan;",
    replace: "if (latest == null) latest = plan;",
    pkg: "packages/planner",
    test: "src/__tests__/types.test.ts",
  },
  {
    name: "runtime: executePlan re-plans a goal that holds an undetermined step",
    file: "packages/runtime/src/plan-execution.ts",
    find: "    const held = this.deps.planEngine.findUnresolvedDelegation(goalId, this.deps.motebitId);",
    replace: "    const held = null as { plan: { plan_id: string } } | null;",
    pkg: "packages/runtime",
    test: "src/__tests__/plan-execution.test.ts",
  },
  {
    name: "runtime: owed payments are not attributed to the run's window",
    file: "packages/runtime/src/goal-run-hold.ts",
    find: "(e) => e.recordedAt >= run.startedAt && (run.endedAt == null || e.recordedAt <= run.endedAt),",
    replace: "(e) => e.recordedAt < 0,",
    pkg: "packages/runtime",
    test: "src/__tests__/goal-run-hold.test.ts",
  },
  {
    name: "cli: a goal with an owed paid result re-fires",
    file: "apps/cli/src/scheduler.ts",
    find: "        if (owed != null) {",
    replace: "        if (owed != null && owed === '') {",
    pkg: "apps/cli",
    test: "src/__tests__/scheduler-undetermined-harness.test.ts",
  },
  {
    name: "cli: a plan_undetermined run is recorded as completed",
    file: "apps/cli/src/scheduler.ts",
    find: "          if (result.undetermined != null) {",
    replace: "          if (result.undetermined != null && result.suspended) {",
    pkg: "apps/cli",
    test: "src/__tests__/scheduler-undetermined-harness.test.ts",
  },
  {
    name: "cli: a refused plan (undetermined) counts as a failure",
    file: "apps/cli/src/scheduler.ts",
    find: "          if (isDelegationUndetermined(err)) {",
    replace: "          if (isDelegationUndetermined(err) && msg === '') {",
    pkg: "apps/cli",
    test: "src/__tests__/scheduler-undetermined-harness.test.ts",
  },
  {
    name: "desktop: a goal with an owed paid result re-fires",
    file: "apps/desktop/src/goal-scheduler.ts",
    // Re-targeted in round 3: the hold now lives in executeGoalOnce.
    find: "    if (runtime == null || (await this.paidResultsOwed(goal.goal_id, invoke, runtime))) {",
    replace: "    if (runtime == null) {",
    pkg: "apps/desktop",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "desktop: an undetermined run counts as a failure",
    file: "apps/desktop/src/goal-scheduler.ts",
    find: "      if (isDelegationUndetermined(err)) {",
    replace: "      if (isDelegationUndetermined(err) && msg === '') {",
    pkg: "apps/desktop",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "desktop: TauriPlanStore.getPlanForGoal returns the first plan, not the latest",
    file: "apps/desktop/src/tauri-storage.ts",
    find: "if (latest == null || plan.created_at >= latest.created_at) latest = plan;",
    replace: "if (latest == null) latest = plan;",
    pkg: "apps/desktop",
    test: "src/__tests__/tauri-storage.test.ts",
  },
  {
    name: "mobile: a goal with an owed paid result re-fires",
    file: "apps/mobile/src/goal-scheduler.ts",
    find: "        if (this.paidResultsOwed(goal.goal_id, runtime)) continue;",
    replace: "        if (this.paidResultsOwed(goal.goal_id, runtime) && now < 0) continue;",
    pkg: "apps/mobile",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "mobile: an undetermined run counts as a failure",
    file: "apps/mobile/src/goal-scheduler.ts",
    find: "          if (isDelegationUndetermined(err)) this.finishGoalAwaitingResult(goal, msg, now);",
    replace:
      "          if (isDelegationUndetermined(err) && msg === '') this.finishGoalAwaitingResult(goal, msg, now);",
    pkg: "apps/mobile",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "web: a goal with an owed paid result re-fires",
    file: "apps/web/src/goal-scheduler.ts",
    find: '      if (paidResultsOwed(goal.goal_id) != null) return { outcome: "skipped" };',
    replace: '      if (paidResultsOwed(goal.goal_id) === "") return { outcome: "skipped" };',
    pkg: "apps/web",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "web: an undetermined once-goal plan reports as fired",
    file: "apps/web/src/goal-scheduler.ts",
    find: "        if (awaiting != null) {",
    replace: "        if (awaiting != null && failed) {",
    pkg: "apps/web",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  // ── Round 2 ─────────────────────────────────────────────────────────────
  {
    name: "planner: no in-process plan lock (two drivers in one process)",
    file: "packages/planner/src/plan-lease.ts",
    find: "    if (this.held.has(planId)) return false;",
    replace: "",
    pkg: "packages/planner",
    test: "src/__tests__/concurrent-drivers-harness.test.ts",
  },
  {
    name: "planner: no persisted plan lease (two drivers in two processes)",
    file: "packages/planner/src/plan-lease.ts",
    find: '    typeof store === "object" &&',
    replace: '    false && typeof store === "object" &&',
    pkg: "packages/planner",
    test: "src/__tests__/concurrent-drivers-harness.test.ts",
  },
  {
    name: "planner: recovery drives a plan without taking its lease",
    file: "packages/planner/src/plan-engine.ts",
    find: '      const release = this.acquireDriver(plan.plan_id);\n      if (release == null) {\n        yield { type: "plan_busy", plan };\n        continue;\n      }',
    replace: "      const release = (): void => {};",
    pkg: "packages/planner",
    test: "src/__tests__/concurrent-drivers-harness.test.ts",
  },
  {
    name: "planner: the step's Idempotency-Key is random per call",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "  return `plan-step:${step.plan_id}:${step.step_id}:${rotation}`;",
    replace: "  return `plan-step:${crypto.randomUUID()}:${rotation}`;",
    pkg: "packages/planner",
    test: "src/__tests__/delegation-result-recovery.test.ts",
  },
  {
    name: "planner: isDelegationUndetermined reads only the top-level error",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "e instanceof Error && depth < 16;",
    replace: "e instanceof Error && depth < 1;",
    pkg: "packages/planner",
    test: "src/__tests__/delegation-result-recovery.test.ts",
  },
  {
    name: "runtime: an unfinished run's window ignores the next run's start",
    file: "packages/runtime/src/goal-run-hold.ts",
    find: "    const ends = [next, bound].filter((x): x is number => x != null);",
    replace: "    const ends = [bound].filter((x): x is number => x != null);",
    pkg: "packages/runtime",
    test: "src/__tests__/goal-run-hold.test.ts",
  },
  {
    name: "desktop: a run's start is not recorded before it can pay",
    file: "apps/desktop/src/goal-scheduler.ts",
    find: "INSERT OR REPLACE INTO goal_outcomes (outcome_id, goal_id, motebit_id, ran_at, status, summary, tool_calls_made, memories_formed, error_message)\n              VALUES (?, ?, ?, ?, 'running'",
    replace:
      "SELECT 1 WHERE ? IS NOT NULL OR ? IS NOT NULL OR ? IS NOT NULL OR ? IS NOT NULL OR 'running'",
    pkg: "apps/desktop",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "mobile: a run's start is not recorded before it can pay",
    file: "apps/mobile/src/goal-scheduler.ts",
    find: "          goalStore.insertOutcome({\n            outcome_id: runId,",
    replace: "          void ({\n            outcome_id: runId,",
    pkg: "apps/mobile",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "web: a fire that never finished is ignored by the hold",
    file: "apps/web/src/goal-scheduler.ts",
    find: '        (r) => r.goal_id === goalId && r.status !== "skipped",',
    replace:
      '        (r) => r.goal_id === goalId && r.status !== "skipped" && r.status !== "running",',
    pkg: "apps/web",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "web: a finished fire's window has no end bound",
    file: "apps/web/src/goal-scheduler.ts",
    find: "endedAt: r.finished_at }",
    replace: "endedAt: null }",
    pkg: "apps/web",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "web: a held once-goal fire is reported as an error",
    file: "apps/web/src/goal-scheduler.ts",
    find: '          return { outcome: "awaiting_result", reason };',
    replace: '          return { outcome: "error", error: reason };',
    pkg: "apps/web",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  // ── Round 3 ─────────────────────────────────────────────────────────────
  {
    name: "planner: the lease is not renewed per step",
    file: "packages/planner/src/plan-engine.ts",
    find: "        if (!this.renewDriver(plan.plan_id)) {",
    replace: "        if (false as boolean) {",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: the step is not re-read under the lease",
    file: "packages/planner/src/plan-engine.ts",
    find: "const step = this.store.getStep(steps[i]!.step_id) ?? steps[i]!;",
    replace: "const step = steps[i]!;",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: resumeLeased does not re-read the plan's status",
    file: "packages/planner/src/plan-engine.ts",
    find: "    if (!plan || plan.status !== PlanStatus.Active) return;",
    replace: "    if (!plan) return;",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: a re-plan's child plan is not leased",
    file: "packages/planner/src/plan-engine.ts",
    find: "const releaseChild = this.acquireDriver(newPlan.plan_id);",
    replace: "const releaseChild = ((): (() => void) | null => () => {})();",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: the lease TTL ignores the delegation timeout",
    file: "packages/planner/src/plan-engine.ts",
    find: "      3 * (this.config.delegationTimeoutMs ?? 300_000),",
    replace: "      0,",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: a held step with no task id is never re-posted (wedged)",
    file: "packages/planner/src/plan-engine.ts",
    find: "      adapter?.resubmitsIdempotently === true &&",
    replace: "      false &&",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: a held step is re-posted past the relay's idempotency window",
    file: "packages/planner/src/plan-engine.ts",
    find: "      this.leaseNow() - step.started_at <",
    replace: "      0 * this.leaseNow() - step.started_at <",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: a re-post restarts the step's submission clock",
    file: "packages/planner/src/plan-engine.ts",
    find: "            step.status === StepStatus.Running && step.started_at != null",
    replace: "            false as boolean",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "planner: a 409 naming the task is ignored",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "    if (named != null) return admittedAs(named);",
    replace: '    if (named === "") return admittedAs(named);',
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "cli: the http adapter uses a random Idempotency-Key",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "      let idempotencyKey = planStepIdempotencyKey(step, rotation);",
    replace: "      let idempotencyKey = crypto.randomUUID();",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "cli: the http adapter ignores a 409 naming the task",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "      if (named != null) return admittedAs(named);",
    replace: '      if (named === "") return admittedAs(named);',
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "desktop: a run whose start write fails runs anyway",
    file: "apps/desktop/src/goal-scheduler.ts",
    find: "    } catch {\n      this._goalExecuting = false;\n      this._currentGoalId = null;\n      this._goalStatusCallback?.(false);\n      return false;\n    }\n\n    try {",
    replace: "    } catch {\n      // tampered\n    }\n\n    try {",
    pkg: "apps/desktop",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "desktop: the hold window is cut at the wall clock again",
    file: "apps/desktop/src/goal-scheduler.ts",
    find: "goalRunWindows(rows.map((r) => ({ startedAt: r.ran_at, endedAt: null }))),",
    replace:
      "goalRunWindows(\n          rows.map((r) => ({ startedAt: r.ran_at, endedAt: null })),\n          { maxRunMs: GOAL_WALL_CLOCK_MS },\n        ),",
    pkg: "apps/desktop",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "desktop: plan_busy is treated as a failure",
    file: "apps/desktop/src/goal-scheduler.ts",
    find: '          throw Object.assign(new Error("the plan is being settled by another run"), {\n            undetermined: true,\n          });',
    replace: '          throw new Error("the plan is being settled by another run");',
    pkg: "apps/desktop",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "mobile: plan_busy is treated as a failure",
    file: "apps/mobile/src/goal-scheduler.ts",
    find: '          throw Object.assign(new Error("the plan is being settled by another run"), {\n            undetermined: true,\n          });',
    replace: '          throw new Error("the plan is being settled by another run");',
    pkg: "apps/mobile",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  {
    name: "web: plan_busy is treated as a failure",
    file: "apps/web/src/goal-scheduler.ts",
    find: '                awaiting = "the plan is being settled by another run";',
    replace: '                failed = true;\n                failureReason = "busy";',
    pkg: "apps/web",
    test: "src/__tests__/goal-scheduler.test.ts",
  },
  // ── Round 4 ─────────────────────────────────────────────────────────────
  {
    name: "planner: a 404 on the step's task is treated as a failure (rotates, pays again)",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "        throw new DelegationUndeterminedError(\n          step.description,\n          new Error(`Delegated task ${task_id} is no longer known to the relay (404)`),\n        );",
    replace:
      "        throw conclusive(`Delegated task ${task_id} expired at the relay without a result`);",
    pkg: "packages/planner",
    test: "src/__tests__/submission-lifecycle-harness.test.ts",
  },
  {
    name: "planner: any non-uncertain error rotates the key (not only positive evidence)",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "        if (lastError.conclusive === true) {\n          rotation++;",
    replace: "        if (lastError.deliveryUncertain !== true) {\n          rotation++;",
    pkg: "packages/planner",
    test: "src/__tests__/delegation-result-recovery.test.ts",
  },
  {
    name: "planner: a 5xx on submission is treated as a refusal",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "      if (resp.status >= 500) {\n        throw deliveryUncertain(",
    replace: "      if (resp.status >= 600) {\n        throw deliveryUncertain(",
    pkg: "packages/planner",
    test: "src/__tests__/delegation.test.ts",
  },
  {
    name: "planner: the adapter starts every call at rotation 0",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "    let rotation = stepRotation(step);",
    replace: "    let rotation = 0;",
    pkg: "packages/planner",
    test: "src/__tests__/delegation-result-recovery.test.ts",
  },
  {
    name: "planner: the adapter does not report a rotation",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "          onRotate?.(rotation);\n        }\n\n        // Don't retry non-retryable errors (submission failures, not timeouts)",
    replace:
      "        }\n\n        // Don't retry non-retryable errors (submission failures, not timeouts)",
    pkg: "packages/planner",
    test: "src/__tests__/submission-lifecycle-harness.test.ts",
  },
  {
    name: "planner: a rotation does not clear the old task id",
    file: "packages/planner/src/plan-engine.ts",
    find: '                  retry_count: rotation,\n                  delegation_task_id: "",',
    replace: "                  retry_count: rotation,",
    pkg: "packages/planner",
    test: "src/__tests__/round4-890.test.ts",
  },
  {
    name: "planner: a rotation is not recorded on the step",
    file: "packages/planner/src/plan-engine.ts",
    find: '                  retry_count: rotation,\n                  delegation_task_id: "",',
    replace: '                  delegation_task_id: "",',
    pkg: "packages/planner",
    test: "src/__tests__/round4-890.test.ts",
  },
  {
    name: "planner (T2): a held step with no submission time is re-posted",
    file: "packages/planner/src/plan-engine.ts",
    find: "      step.started_at != null &&\n",
    replace: "",
    pkg: "packages/planner",
    test: "src/__tests__/round3-890.test.ts",
  },
  {
    name: "cli: a 404 on the step's task is treated as a failure",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "        throw new DelegationUndeterminedError(\n          step.description,\n          new Error(`Delegated task ${taskId} is no longer known to the relay (404)`),\n        );",
    replace:
      "        const err: StepAttemptError = new Error(`Delegated task ${taskId} expired`);\n        err.conclusive = true;\n        throw err;",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "cli: a 5xx on submission is treated as a refusal",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "      if (resp.status >= 500) {\n        throw unconfirmed(",
    replace: "      if (resp.status >= 600) {\n        throw unconfirmed(",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "cli: the adapter starts every call at rotation 0",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "      let rotation = stepRotation(step);",
    replace: "      let rotation = 0;",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "cli: the adapter does not report a rotation",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "            onRotate?.(rotation);",
    replace: "",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "cli (T4): the http adapter does not declare idempotent re-posting",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "    resubmitsIdempotently: true,",
    replace: "",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "relay: the archive answers for a task another agent's key admitted",
    file: "services/relay/src/receipts-store.ts",
    find: "WHERE k.task_id = r.task_id AND k.motebit_id = ? AND k.created_at >= ?",
    replace: "WHERE k.task_id = r.task_id AND (k.motebit_id = ? OR 1) AND k.created_at >= ?",
    pkg: "services/relay",
    test: "src/__tests__/task-archive-890.test.ts",
  },
  {
    name: "relay: the archive answers past the idempotency window",
    file: "services/relay/src/receipts-store.ts",
    find: "WHERE k.task_id = r.task_id AND k.motebit_id = ? AND k.created_at >= ?",
    replace: "WHERE k.task_id = r.task_id AND k.motebit_id = ? AND (k.created_at >= ? OR 1)",
    pkg: "services/relay",
    test: "src/__tests__/task-archive-890.test.ts",
  },
  {
    name: "relay: an evicted task is not answered from the archive",
    file: "services/relay/src/tasks.ts",
    find: "        if (archived != null) {\n          const receipt = JSON.parse(archived) as ExecutionReceipt;",
    replace:
      "        if (archived == null && archived != null) {\n          const receipt = JSON.parse(archived) as ExecutionReceipt;",
    pkg: "services/relay",
    test: "src/__tests__/task-archive-890.test.ts",
  },
  // ── Round 5 ─────────────────────────────────────────────────────────────
  {
    name: "planner: a non-409 response that names its task is read as a refusal",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "    const named = await taskNamedBy409(resp);\n    if (named != null) return admittedAs(named);\n    if (resp.status !== 409) return resp;",
    replace:
      "    if (resp.status !== 409) return resp;\n    const named = await taskNamedBy409(resp);\n    if (named != null) return admittedAs(named);",
    pkg: "packages/planner",
    test: "src/__tests__/submission-lifecycle-harness.test.ts",
  },
  {
    name: "planner: a failed receipt from a non-routed signer counts as evidence",
    file: "packages/planner/src/delegation-adapter.ts",
    find: '      if (routed != null && routed !== "" && receipt.motebit_id !== routed) {',
    replace: "      if (false as boolean) {",
    pkg: "packages/planner",
    test: "src/__tests__/round5-890.test.ts",
  },
  {
    name: "planner: a receipt bound to another task settles the step's delegation",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "      if (!receiptBoundTo(receipt, task_id)) {",
    replace: "      if (false as boolean) {",
    pkg: "packages/planner",
    test: "src/__tests__/round5-890.test.ts",
  },
  {
    name: "planner: a polled receipt bound to another task settles a held step",
    file: "packages/planner/src/delegation-adapter.ts",
    find: "      if (!receiptBoundTo(data.receipt, taskId)) return null;\n",
    replace: "",
    pkg: "packages/planner",
    test: "src/__tests__/round5-890.test.ts",
  },
  {
    name: "planner: a rotation does not restamp the key's submission time",
    file: "packages/planner/src/plan-engine.ts",
    find: "                  started_at: rotatedAt,\n",
    replace: "",
    pkg: "packages/planner",
    test: "src/__tests__/submission-lifecycle-harness.test.ts",
  },
  {
    name: "cli: a non-409 response that names its task is read as a refusal",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "      const named = await taskNamedBy409(resp);\n      if (named != null) return admittedAs(named);\n      if (resp.status !== 409) return resp;",
    replace:
      "      if (resp.status !== 409) return resp;\n      const named = await taskNamedBy409(resp);\n      if (named != null) return admittedAs(named);",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "cli: a failed receipt from a non-routed signer counts as evidence",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: '        if (routed != null && routed !== "" && receipt.motebit_id !== routed) {',
    replace: "        if (false as boolean) {",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "cli: a receipt bound to another task settles the delegation",
    file: "apps/cli/src/subcommands/delegate.ts",
    find: "      if (!receiptBoundTo(receipt, taskId)) {",
    replace: "      if (false as boolean) {",
    pkg: "apps/cli",
    test: "src/__tests__/delegate-http-adapter.test.ts",
  },
  {
    name: "relay: the MCP forward accepts a receipt signed by another identity",
    file: "services/relay/src/task-routing.ts",
    find: "          (receiptData.motebit_id !== agentId || receiptRelayTaskId(receiptData) !== taskId)",
    replace: "          (receiptRelayTaskId(receiptData) !== taskId)",
    pkg: "services/relay",
    test: "src/__tests__/forward-receipt-signer-890.test.ts",
  },
  {
    name: "relay: the archive answers a caller asking about another agent's path",
    file: "services/relay/src/tasks.ts",
    find: "      if (callerMotebitId == null || callerMotebitId === motebitId) {",
    replace: "      if (true as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/task-archive-890.test.ts",
  },
  {
    name: "relay r6 (A): admission does not record the path agent as the task's executor",
    file: "services/relay/src/tasks.ts",
    find: "    recordTaskRoute(moteDb.db, taskId, motebitId);\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (A): an MCP presentation does not record its worker",
    file: "services/relay/src/tasks.ts",
    find: "      recordTaskRoute(moteDb.db, taskId, workerId);\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (A): a pinned socket dispatch does not record its worker",
    file: "services/relay/src/tasks.ts",
    find: "        recordTaskRoute(moteDb.db, taskId, pinnedId);\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (A): a federated P2P forward does not record its worker and peer",
    file: "services/relay/src/tasks.ts",
    find: "      recordTaskRoute(moteDb.db, taskId, targetId, peerRelayId);\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/federation-e2e.test.ts",
  },
  {
    name: "relay r6 (A): a ranked federated forward does not record its worker and peer",
    file: "services/relay/src/tasks.ts",
    find: "                  recordTaskRoute(moteDb.db, taskId, selId, plannedPeer);\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/federation-e2e.test.ts",
  },
  {
    name: "relay r6 (A): a ranked socket dispatch does not record its worker",
    file: "services/relay/src/tasks.ts",
    find: "                  recordTaskRoute(moteDb.db, taskId, selId);\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/delegation-e2e.test.ts",
  },
  {
    name: "relay r6 (A): a submitter-presented task does not record the worker its token binds",
    file: "services/relay/src/tasks.ts",
    find: "    if (submitterPresents) recordTaskRoute(moteDb.db, taskId, intendedWorker);\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (A): the executor relay does not record its own agent for a forwarded task",
    file: "services/relay/src/federation-callbacks.ts",
    find: '        recordTaskRoute(\n          moteDb.db,\n          verified.taskId,\n          verified.targetAgent,\n          "",\n          "inbound_forward",\n          verified.originRelay,\n        );\n',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/federation-e2e.test.ts",
  },
  {
    name: "relay r6 (B) \u2192 r8 chokepoint: a local door accepts a receipt from an identity the task was never handed to",
    file: "services/relay/src/task-answer.ts",
    find: "    routed = isRoutedExecutor(\n      db,",
    replace: "    routed = true || isRoutedExecutor(\n      db,",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B): a route admits any signer",
    file: "services/relay/src/task-routing.ts",
    find: "  return routes.some((r) => r.executor_id === signer && r.via_peer === viaPeer);",
    replace: "  return routes.some((r) => r.via_peer === viaPeer);",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B): a route admits its executor through any peer",
    file: "services/relay/src/task-routing.ts",
    find: "  return routes.some((r) => r.executor_id === signer && r.via_peer === viaPeer);",
    replace: "  return routes.some((r) => r.executor_id === signer);",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B): an unrouted task admitted after the record is answerable by its own agent",
    file: "services/relay/src/task-routing.ts",
    find: "      admittedBeforeTaskRoutes(db, legacy.submittedAt)",
    replace: "      true",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B) \u2192 r8 chokepoint: the federation door accepts a result from an unrouted executor or peer",
    file: "services/relay/src/task-answer.ts",
    find: '        : isRoutedExecutor(db, taskId, receipt.motebit_id, door.viaPeer, null, "admission");',
    replace: "        : true;",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B) \u2192 r8 chokepoint: a door accepts a receipt bound to another task",
    file: "services/relay/src/task-answer.ts",
    find: "  if (boundTo !== taskId) {",
    replace: "  if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B) \u2192 r8 chokepoint: a receipt with no key to verify it is accepted unverified",
    file: "services/relay/src/task-answer.ts",
    find: '    return { refusal: "no_key" };',
    replace: '    return { key: "" };',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B/P2): the MCP forward accepts a receipt the worker bound to another task",
    file: "services/relay/src/task-routing.ts",
    find: "          (receiptData.motebit_id !== agentId || receiptRelayTaskId(receiptData) !== taskId)",
    replace: "          (receiptData.motebit_id !== agentId)",
    pkg: "services/relay",
    // Round 8: the chokepoint binds every door's receipt to its task too, so
    // the forward's own layer is proven by its unit test.
    test: "src/__tests__/forward-receipt-signer-890.test.ts",
  },
  {
    name: "relay r6 (B) \u2192 r8: the MCP forward reports a receipt ingestion refused as accepted",
    file: "services/relay/src/task-routing.ts",
    find: "              ingested = (await onReceipt(receiptData)) === true;",
    replace: "              await onReceipt(receiptData);\n              ingested = true;",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (B): the MCP callback does not report ingestion's refusal",
    file: "services/relay/src/tasks.ts",
    find: "          return ingested.verified;",
    replace: "          return true;",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (C): the archive answers a receipt from any signer, routed or not",
    file: "services/relay/src/receipts-store.ts",
    find: "             WHERE t.task_id = r.task_id AND t.executor_id = r.motebit_id",
    replace: "             WHERE t.task_id = r.task_id",
    pkg: "services/relay",
    test: "src/__tests__/task-archive-890.test.ts",
  },
  {
    name: "relay r6 (C): the archive answers the newest receipt, not the completed one",
    file: "services/relay/src/receipts-store.ts",
    find: "        ORDER BY (r.status = 'completed') DESC, r.received_at DESC",
    replace: "        ORDER BY r.received_at DESC",
    pkg: "services/relay",
    test: "src/__tests__/task-archive-890.test.ts",
  },
  {
    name: "relay r6 (D): a nested child is archived under the top-level key of its task",
    file: "services/relay/src/receipts-store.ts",
    find: '  const key = depth === 0 ? taskId : `${taskId}${NESTED_KEY_SEP}${parentTaskId ?? ""}`;',
    replace: "  const key = taskId;",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (D): an audit read no longer finds a nested child under its namespaced key",
    file: "services/relay/src/receipts-store.ts",
    find: "          AND (task_id = ? OR substr(task_id, 1, ?) = ?)",
    replace: "          AND (task_id = ? OR (? = 0 AND ? = ''))",
    pkg: "services/relay",
    test: "src/__tests__/signed-receipt-e2e.test.ts",
  },
  {
    name: "relay r6 (C): the origin never archives a verified federated receipt",
    // r9 C2: every door archives in the one door routine (admitReceipt).
    file: "services/relay/src/task-answer.ts",
    find: "  const newlyArchived = persistReceiptChain(deps.db, answer);",
    replace: "  const newlyArchived = true;",
    // r9: the ANSWER archive answers the poll too — sever both.
    also: [
      {
        file: "services/relay/src/task-queue.ts",
        find: "      if (current.receipt != null) {\n        this.stmtArchiveAnswer.run(",
        replace: "      if (false as boolean) {\n        this.stmtArchiveAnswer.run(",
      },
    ],
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 \u2192 r8 chokepoint: the answer is never persisted to the durable queue (the poll never sees it)",
    file: "services/relay/src/task-queue.ts",
    find: "      if (!this.writeRow(taskId, current, expectedVersion + 1, expectedVersion)) {",
    replace: "      if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (retention): the route sweep deletes nothing",
    file: "services/relay/src/task-routing.ts",
    find: "    .run(now - TASK_ROUTE_RETENTION_MS);",
    replace: "    .run(0);",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (retention): routes are swept inside the idempotency window",
    file: "services/relay/src/task-routing.ts",
    find: "export const TASK_ROUTE_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;",
    replace: "export const TASK_ROUTE_RETENTION_MS = 60 * 60 * 1000;",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (legacy): the archive answers a nested row that squats a task's plain key",
    file: "services/relay/src/receipts-store.ts",
    find: "        WHERE r.task_id = ? AND r.depth = 0",
    replace: "        WHERE r.task_id = ?",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r6 (legacy): an audit read serves a nested copy over the task's own top-level receipt",
    file: "services/relay/src/receipts-store.ts",
    find: "        ORDER BY depth, received_at",
    replace: "        ORDER BY depth DESC, received_at",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): a colliding forward is refused only while the id is QUEUED — the queue store dropped",
    file: "services/relay/src/federation-callbacks.ts",
    find: "      if (queued != null) {",
    replace: "      if (queued != null && (false as boolean)) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): the same peer re-forwarding its queued task is not answered `duplicate`",
    file: "services/relay/src/federation-callbacks.ts",
    find: "        if (queued.origin_relay === verified.originRelay) {",
    replace: "        if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): an id an own admission ROUTED is not refused",
    file: "services/relay/src/task-routing.ts",
    find: '  if (taskRoutes(db, taskId, "admission").length > 0) return "in_use";\n',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): an id an Idempotency-Key admitted is not refused",
    file: "services/relay/src/task-routing.ts",
    find: '  if (key != null) return "in_use";\n',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): an id with an archived receipt is not refused",
    file: "services/relay/src/task-routing.ts",
    find: '  if (receipt != null) return "in_use";\n',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): a peer's retry of a task held only by its inbound route is re-run",
    file: "services/relay/src/federation-callbacks.ts",
    find: '      if (known === "inbound_held") {',
    replace: "      if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): an id in use is not refused at all",
    file: "services/relay/src/federation-callbacks.ts",
    find: '      if (known === "in_use") return collision(verified.taskId, verified.originRelay, "stored");\n',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (inbound door): a task id in use answers 429, not 409",
    file: "services/relay/src/federation.ts",
    find: ' || result.reason === "task_id_in_use"',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (route origin write): the inbound forward records its route as an own admission",
    file: "services/relay/src/federation-callbacks.ts",
    find: '          "inbound_forward",\n          verified.originRelay,',
    replace: '          "admission",\n          verified.originRelay,',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (route origin read): routes are read without their origin",
    file: "services/relay/src/task-routing.ts",
    find: "WHERE task_id = ? AND origin = ?",
    replace: "WHERE task_id = ? AND ? IS NOT NULL",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (archive origin filter): the archive answers an inbound forward's executor",
    file: "services/relay/src/receipts-store.ts",
    find: "               AND t.origin = 'admission'\n",
    replace: "",
    // r9: the answer archive is read first — its origin filter too.
    also: [
      {
        file: "services/relay/src/receipts-store.ts",
        find: "                 AND t.origin = 'admission'\n",
        replace: "",
      },
    ],
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r7 \u2192 r8 chokepoint (local door origin): an own admission is answered by an inbound forward's route",
    file: "services/relay/src/task-answer.ts",
    find: '      entry.origin_relay != null ? "inbound_forward" : "admission",',
    replace: '      "inbound_forward",',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 \u2192 r8 chokepoint (local door origin): an inbound task is answered only by admission routes",
    file: "services/relay/src/task-answer.ts",
    find: '      entry.origin_relay != null ? "inbound_forward" : "admission",',
    replace: '      "admission",',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 \u2192 r8 chokepoint (federation door origin): a federated result is checked against inbound routes",
    file: "services/relay/src/task-answer.ts",
    find: 'door.viaPeer, null, "admission");',
    replace: 'door.viaPeer, null, "inbound_forward");',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (migration v51): existing routes default to inbound, not admission",
    file: "services/relay/src/migrations.ts",
    find: "ADD COLUMN origin TEXT NOT NULL DEFAULT 'admission'",
    replace: "ADD COLUMN origin TEXT NOT NULL DEFAULT 'inbound_forward'",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (migration v51): a still-queued inbound route is not relabelled",
    file: "services/relay/src/migrations.ts",
    find: "UPDATE relay_task_routes SET origin = 'inbound_forward'",
    replace: "UPDATE relay_task_routes SET origin = 'admission'",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r7 (P1 positive check): the MCP forward accepts a receipt ingestion never positively accepted",
    file: "services/relay/src/task-routing.ts",
    find: "              ingested = (await onReceipt(receiptData)) === true;",
    replace: "              ingested = (await onReceipt(receiptData)) !== undefined;",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    // Round 8: the settled half of this guard is the chokepoint's write-once rule
    // (tampered below); the gone half answers `false`, and the MCP door's
    // acceptance report is now observed by the ANSWER matrix (evicted cells).
    name: "relay r7 \u2192 r8 (P1 return false): a gone entry's late MCP answer is reported accepted",
    file: "services/relay/src/tasks.ts",
    find: "          if (!mcpEntry) return false;",
    replace: "          if (!mcpEntry) return true;",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 chokepoint (signature): a receipt failing its signature is answered",
    file: "services/relay/src/task-answer.ts",
    find: '    return { refusal: "bad_signature" };\n  }\n  if (door.kind === "federation_result") {',
    replace: '    return { key: pubKeyHex };\n  }\n  if (door.kind === "federation_result") {',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 chokepoint (executor): a signer the task was never handed to answers it, at every door",
    file: "services/relay/src/task-answer.ts",
    find: "  if (!routed) {",
    replace: "  if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 chokepoint (write-once): an answered or settled entry takes a new answer",
    file: "services/relay/src/task-answer.ts",
    find: '  if (rule === "answered") {',
    replace: "  if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 chokepoint (write-once rule): an answered entry is treated as unanswered",
    file: "services/relay/src/task-answer.ts",
    find: '  if (frozen) return "answered";\n  if (prior == null) return "take";',
    replace: '  if (prior == null || prior != null) return "take";',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 chokepoint (completed outranks failed): a verified completed never replaces a failed",
    file: "services/relay/src/task-answer.ts",
    find: '  if (prior.status !== "completed" && incoming.status === "completed") return "replace";',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r8 door (result POST): the door writes a refused answer itself, around the chokepoint",
    file: "services/relay/src/tasks.ts",
    find: '    if (!ingestionResult.verified) {\n      if (ingestionResult.refusal === "answered") {',
    replace:
      '    if (!ingestionResult.verified && ingestionResult.refusal === "answered") {\n      const bypass = taskQueue.get(taskId);\n      if (bypass) {\n        bypass.receipt = receipt;\n        taskQueue.set(taskId, bypass);\n      }\n      return c.json({ status: "already_settled" });\n    }\n    if (!ingestionResult.verified) {\n      if (ingestionResult.refusal === "answered") {',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 door (MCP forward): the forward writes the worker's receipt itself, around the chokepoint",
    file: "services/relay/src/task-routing.ts",
    find: "          let ingested = false;",
    replace:
      "          let ingested = false;\n          {\n            const bypass = _taskQueue.get(taskId);\n            if (bypass) {\n              bypass.receipt = receiptData;\n              bypass.task.status = receiptData.status;\n              _taskQueue.set(taskId, bypass);\n            }\n          }",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 door (federation result): the door writes a refused answer itself, around the chokepoint",
    file: "services/relay/src/federation-callbacks.ts",
    find: '      if (!admitted.took) {\n        logger.error("federation.result_not_taken", {',
    replace:
      '      if (!admitted.took && admitted.refusal === "answered") {\n        entry.receipt = verified.receipt;\n        taskQueue.set(verified.taskId, entry);\n        return;\n      }\n      if (!admitted.took) {\n        logger.error("federation.result_not_taken", {',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 door (local ingestion): handleReceiptIngestion ignores the chokepoint's refusal",
    file: "services/relay/src/tasks.ts",
    find: "  if (!admission.took) {\n    return {\n      verified: false,",
    replace:
      '  if (!admission.took && admission.refusal === "answered") {\n    return { verified: true, credential_id: null, already_settled: true };\n  }\n  if (!admission.took) {\n    return {\n      verified: false,',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 (P1 peer check): any peer re-forwarding an id held by another peer's inbound route gets `duplicate`",
    file: "services/relay/src/task-routing.ts",
    find: '    return inbound.every((r) => r.from_peer !== "" && r.from_peer === fromPeer)',
    replace: "    return inbound.length > 0",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 (P1 record): the inbound route does not record the forwarding peer",
    file: "services/relay/src/federation-callbacks.ts",
    find: '          "inbound_forward",\n          verified.originRelay,\n        );',
    replace: '          "inbound_forward",\n          "",\n        );',
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  {
    name: "relay r8 (P3 positive-only): an MCP forward with no ingestion callback reports acceptance",
    file: "services/relay/src/task-routing.ts",
    find: "          let ingested = false;\n          if (onReceipt != null) {",
    replace: "          let ingested = onReceipt == null;\n          if (onReceipt != null) {",
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  // ── #890 round 9 — an answer and its settlement are ONE decision ──
  {
    name: "relay r9 (1) frozen: a settled / settlement-claimed answer is replaced by a completed",
    file: "services/relay/src/task-answer.ts",
    find: '  if (frozen) return "answered";\n',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (1) frozen, legacy: an entry answered before the claim counts as unsettled though a settlement row names it",
    file: "services/relay/src/task-answer.ts",
    find: "  return settlementRowsFor(db, taskId).length > 0;\n}",
    replace: "  return false;\n}",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (2) claim-settle: the take does not claim the settlement for its receipt (a replace slips in during the awaits)",
    file: "services/relay/src/task-answer.ts",
    find: "    e.settling = receipt.signature;\n    e.settle_via = door;\n  });\n  if (written == null) {",
    replace: "  });\n  if (written == null) {",
    also: [
      {
        file: "services/relay/src/task-answer.ts",
        find: "  if (answer == null || entry.settling !== answer.signature) {",
        replace: "  if (answer == null) {",
      },
    ],
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (2) the POST door's 409 does not carry the settled answer",
    file: "services/relay/src/tasks.ts",
    find: "            receipt: ingestionResult.answer ?? null,",
    replace: "            receipt: null,",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (3) the answer is not archived with the entry (the poll changes on eviction)",
    file: "services/relay/src/task-queue.ts",
    find: "      if (current.receipt != null) {\n        this.stmtArchiveAnswer.run(",
    replace: "      if (false as boolean) {\n        this.stmtArchiveAnswer.run(",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (3) the archive read ignores the answer table (the ranked audit archive answers instead)",
    file: "services/relay/src/receipts-store.ts",
    find: "  if (answered != null) {",
    replace: "  if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (4) writeAnswer accepts any object as the capability",
    file: "services/relay/src/task-queue.ts",
    find: '    if (typeof cap !== "object" || cap === null || !answerCapabilities.has(cap)) {',
    replace: "    if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (4) the capability can be issued twice",
    file: "services/relay/src/task-queue.ts",
    find: "  if (answerCapabilityIssued) {",
    replace: "  if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (4) TaskQueue.set writes a change of answer without the capability",
    file: "services/relay/src/task-queue.ts",
    find: "    if (answerOf(entry) !== answerOf(stored)) {",
    replace: "    if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (4) TaskQueue.set writes a stale copy (compare-and-set on the answer version off)",
    file: "services/relay/src/task-queue.ts",
    find: "    if ((entry.answer_version ?? 0) !== stored.answer_version) {",
    replace: "    if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (4) TaskQueue.set inserts an answered entry",
    file: "services/relay/src/task-queue.ts",
    find: "      if (\n        entry.receipt != null ||\n        TERMINAL.has(entry.task.status) ||",
    replace: "      if (\n        false ||\n        TERMINAL.has(entry.task.status) ||",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (4) table: a raw SQL UPDATE writes an answer",
    file: "services/relay/src/task-queue.ts",
    find: "        SELECT RAISE(ABORT, 'relay_task_queue: ${guard}, never over a newer answer');",
    replace: "        SELECT 1;",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 (4) table: INSERT OR REPLACE / an answered INSERT writes an answer",
    file: "services/relay/src/task-queue.ts",
    find: "        SELECT RAISE(ABORT, 'relay_task_queue: an entry is inserted unanswered, once; ${guard}');",
    replace: "        SELECT 1;",
    pkg: "services/relay",
    test: "src/__tests__/answer-settlement-890.test.ts",
  },
  {
    name: "relay r9 matrix: the answer archive is off — the eviction dimension goes red",
    file: "services/relay/src/receipts-store.ts",
    find: "  if (answered != null) {",
    replace: "  if (false as boolean) {",
    also: [
      {
        file: "services/relay/src/task-answer.ts",
        find: '  if (frozen) return "answered";\n',
        replace: "",
      },
      // r9 cold review: the table refuses moving a settled answer too.
      {
        file: "services/relay/src/task-queue.ts",
        find: "      SELECT RAISE(ABORT, 'relay_task_queue: a settled answer is frozen — never moved off the receipt its settlement names (#890 r9)');",
        replace: "      SELECT 1;",
      },
    ],
    pkg: "services/relay",
    test: "src/__tests__/receipt-doors-890.test.ts",
  },
  // ── #890 round 9, cold review C1/C2 — one door routine; the tables guard the claim ──
  {
    name: "relay r9 C1: the sub-receipt door pays the sub-task without answering or claiming it",
    file: "services/relay/src/tasks.ts",
    find: "          const subAdmission = await admitReceipt(",
    replace:
      "          const subDirect = taskQueue.get(subRelayTaskId);\n          if (subDirect != null) await settleSubAnswer(subDirect, sub, parentTaskId, depth, subRelayTaskId).catch(() => false);\n          const subAdmission = { took: true } as const;\n          if (false as boolean) await admitReceipt(",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 C2: a repeat whose settlement never completed returns without settling",
    file: "services/relay/src/task-answer.ts",
    find: "  if (answer != null && entry.settled === true) {",
    replace: "  if (answer != null && (entry.settled === true || verdict.repeat)) {",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 C2: the federation settlement row commits without its forward's retry row",
    file: "services/relay/src/federation-callbacks.ts",
    find: "              if (peerInfo) {\n                // First retry at baseDelayMs",
    replace: "              if (false as boolean) {\n                // First retry at baseDelayMs",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 a failed settlement step still marks the entry settled",
    file: "services/relay/src/task-answer.ts",
    find: "  if (done) markTaskSettled(deps.taskQueue, taskId, answer.signature);",
    replace: "  markTaskSettled(deps.taskQueue, taskId, answer.signature);",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 table: a settlement row is written for a receipt its task is not claimed for",
    file: "services/relay/src/task-queue.ts",
    find: "        SELECT RAISE(ABORT, '${t}: a settlement is written only for the receipt the task is claimed for (#890 r9)');",
    replace: "        SELECT 1;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 table: a second settlement row is written for a task",
    file: "services/relay/src/task-queue.ts",
    find: "        SELECT RAISE(ABORT, '${t}: a task settles once — a settlement row already names it (#890 r9)');",
    replace: "        SELECT 1;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 table: a settlement_credit names no settlement row",
    file: "services/relay/src/task-queue.ts",
    find: "        SELECT RAISE(ABORT, 'relay_transactions: a settlement_credit names the settlement row (or dispute) it pays (#890 r9)');",
    replace: "        SELECT 1;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 table: a settled answer is moved off the receipt its settlement names",
    file: "services/relay/src/task-queue.ts",
    find: "      SELECT RAISE(ABORT, 'relay_task_queue: a settled answer is frozen — never moved off the receipt its settlement names (#890 r9)');",
    replace: "      SELECT 1;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 an unanswered entry a settlement row pays adopts any receipt",
    file: "services/relay/src/task-answer.ts",
    find: "      rows.every((row) => rowNames(row, receipt)) &&",
    replace: "      true &&",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 pin: the answers sweep deletes an unsettled claim of a still-queued task",
    file: "services/relay/src/task-routing.ts",
    find: "\n         AND NOT (settled = 0 AND task_id IN (SELECT task_id FROM relay_task_queue))`",
    replace: "`",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 pin: the legacy repeat does not claim the entry's own receipt",
    file: "services/relay/src/task-answer.ts",
    find: "      entry =\n        taskQueue.writeAnswer(ANSWER_CAP, taskId, current.answer_version ?? 0, (e) => {\n          e.settling = receipt.signature;\n          e.settle_via = door;\n        }) ?? current;",
    replace: "      entry = current;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 pin: markTaskSettled marks a receipt the entry is not claimed for",
    file: "services/relay/src/task-answer.ts",
    find: "  if (claimedFor !== receiptSignature) {",
    replace: "  if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 pin: a settled answer's repeat runs the settlement step again",
    file: "services/relay/src/task-answer.ts",
    find: "  if (answer != null && entry.settled === true) {",
    replace: "  if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r9 pin: the federation door's P2P audit leaves the entry unsettled",
    file: "services/relay/src/federation-callbacks.ts",
    find: "            return false;\n          }\n          return true;\n        }",
    replace: "            return false;\n          }\n          return false;\n        }",
    pkg: "services/relay",
    test: "src/__tests__/settlement-doors-890.test.ts",
  },
  {
    name: "relay r10 M1: the executor's settlement row names no receipt (receipt_signature null) \u2014 the honest forward pays nothing",
    file: "services/relay/src/federation-callbacks.ts",
    find: "            canonicalJson(signedRecord),\n            receiptSignature,\n          );",
    replace: "            canonicalJson(signedRecord),\n            null,\n          );",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 M2: admitReceipt re-runs the settlement step though a committed row already names the task",
    file: "services/relay/src/task-answer.ts",
    find: "  if (settlementRowsFor(deps.db, taskId).length > 0) {\n    markTaskSettled(",
    replace: "  if (false as boolean) {\n    markTaskSettled(",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 M5: the claim guard ignores the archived answer's claim (an evicted task takes any receipt's row)",
    file: "services/relay/src/task-queue.ts",
    find: "        OR (NOT EXISTS (SELECT 1 FROM relay_task_queue WHERE task_id = NEW.task_id)\n            AND EXISTS (SELECT 1 FROM relay_task_answers WHERE task_id = NEW.task_id\n              AND settling = NEW.receipt_signature))",
    replace: "        OR 1",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 M5b: the claim guard does not know a task by its archived answer",
    file: "services/relay/src/task-queue.ts",
    find: "        OR EXISTS (SELECT 1 FROM relay_task_answers WHERE task_id = NEW.task_id))`;",
    replace: "        OR 0)`;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 M9: the frozen guard lets a claim move off the receipt a settlement row names",
    file: "services/relay/src/task-queue.ts",
    find: "\n      OR (json_extract(NEW.task_json, '$.settling') IS NOT json_extract(OLD.task_json, '$.settling')\n          AND ${namesOther(\"json_extract(NEW.task_json, '$.settling')\")})",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 M10: the frozen guard lets an answered entry a legacy (unsigned) row pays take another receipt",
    file: "services/relay/src/task-queue.ts",
    find: "(OLD.receipt IS NOT NULL AND ${anyRow})\n               OR ",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (1) straddle: a pre-deploy answer does not adopt the claim when the settlement forward arrives",
    file: "services/relay/src/federation-callbacks.ts",
    find: '      if (workerEntry?.receipt != null && (workerEntry.settling ?? "") === "") {',
    replace: "      if (false as boolean) {",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (1) straddle: an evicted task's archived executor is not paid",
    file: "services/relay/src/federation-callbacks.ts",
    find: "      const workerId = workerEntry?.task.motebit_id ?? archivedWorker;",
    replace: "      const workerId = workerEntry?.task.motebit_id ?? null;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (1) straddle: a peer's forward pays an evicted task of this relay's own admission",
    file: "services/relay/src/federation-callbacks.ts",
    find: " && !ownAdmission",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (1) straddle: the sweep does not claim a pre-deploy inbound answer (lost on eviction)",
    file: "services/relay/src/settlement-recovery.ts",
    find: "  for (const { task_id } of legacy) {",
    replace: "  for (const { task_id } of legacy.slice(0, 0)) {",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (2) strand: a parent's repeat does not re-walk its nested sub-receipts",
    file: "services/relay/src/tasks.ts",
    find: "    if (admission.repeat) {\n      // The parent's identical retry",
    replace: "    if (false as boolean) {\n      // The parent's identical retry",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (2) strand: the re-walk skips the stranded sub-claim too",
    file: "services/relay/src/tasks.ts",
    find: "        if (onlyUnsettledClaims && !strandedClaim) {",
    replace: "        if (onlyUnsettledClaims) {",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) recovery: the sweep finds the claim but never replays it",
    file: "services/relay/src/settlement-recovery.ts",
    find: "      await replay(deps, task_id, entry);",
    replace: "      void entry;",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) recovery: no boot pass",
    file: "services/relay/src/index.ts",
    find: "    : runSettlementRecovery({ graceMs: 0 }).then(",
    replace: "    : Promise.resolve(null).then(",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) recovery: the claim does not record its door (a federation claim replays through the local door)",
    file: "services/relay/src/task-answer.ts",
    find: "    e.settling = receipt.signature;\n    e.settle_via = door;\n  });\n  if (written == null) {",
    replace: "    e.settling = receipt.signature;\n  });\n  if (written == null) {",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) recovery: the periodic pass takes a fresh claim out from under its own door (no grace)",
    file: "services/relay/src/settlement-recovery.ts",
    find: "          AND a.answered_at <= ?",
    replace: "          AND a.answered_at <= ? + 1e15",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) recovery: expiry deletes a claimed-but-unsettled entry",
    file: "services/relay/src/task-queue.ts",
    find: "`DELETE FROM relay_task_queue WHERE expires_at < ? AND NOT ${heldClaim}`",
    replace: "`DELETE FROM relay_task_queue WHERE expires_at < ? AND NOT (0 AND ? IS NULL)`",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) recovery: the size cap evicts a claimed-but-unsettled entry",
    file: "services/relay/src/task-queue.ts",
    find: "FROM relay_task_queue WHERE NOT ${heldClaim} ORDER BY",
    replace: "FROM relay_task_queue WHERE NOT (0 AND ? IS NULL) ORDER BY",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) delivery: the executor sends its federation result once, with no outbox row",
    file: "services/relay/src/tasks.ts",
    find: "        enqueueResultDelivery(moteDb.db, taskId, entry.origin_relay);\n",
    replace: "\n",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (3) delivery: a failed delivery is never retried",
    file: "services/relay/src/federation.ts",
    find: '  if (attempts >= row.max_attempts) return finish("exhausted", error);',
    replace: '  return finish("exhausted", error);',
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (5) recovery loop: a sweep arriving mid-pass queues a pass behind it (chain, not skip)",
    file: "services/relay/src/index.ts",
    find: "    if (recoveryInFlight != null) return recoveryInFlight;\n    const run = recoverSettlements(recoveryDeps, { ...opts, signal: recoveryAbort.signal });",
    replace:
      "    const run = (recoveryInFlight ?? Promise.resolve(null))\n      .catch(() => null)\n      .then(() => recoverSettlements(recoveryDeps, { ...opts, signal: recoveryAbort.signal }));",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (5) recovery loop: the pass never checks the freeze (P6)",
    file: "services/relay/src/settlement-recovery.ts",
    find: '    else if (deps.isFrozen?.() === true) report.halted = "frozen";\n',
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
  {
    name: "relay r10 (5) recovery loop: close() does not abort the pass in flight (P5)",
    file: "services/relay/src/index.ts",
    find: "    recoveryAbort.abort();\n",
    replace: "",
    pkg: "services/relay",
    test: "src/__tests__/settlement-liveness-890.test.ts",
  },
];

/** Tampers in these packages change a `dist` that app tests import. */
const DIST_PACKAGES = new Set(["packages/planner", "packages/runtime"]);

function run(cmd: string, args: string[], cwd: string): boolean {
  try {
    execFileSync(cmd, args, { cwd: path.join(ROOT, cwd), stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

let failures = 0;
for (const t of TAMPERS) {
  const abs = path.join(ROOT, t.file);
  const original = readFileSync(abs, "utf8");
  if (!original.includes(t.find)) {
    console.error(`STALE  ${t.name}: text not found in ${t.file}`);
    failures++;
    continue;
  }
  const extra = (t.also ?? []).map((a) => {
    const aAbs = path.join(ROOT, a.file);
    return { ...a, abs: aAbs, original: readFileSync(aAbs, "utf8") };
  });
  const staleExtra = extra.find((a) => !a.original.includes(a.find));
  if (staleExtra != null) {
    console.error(`STALE  ${t.name}: text not found in ${staleExtra.file}`);
    failures++;
    continue;
  }
  writeFileSync(abs, original.replace(t.find, t.replace));
  for (const a of extra) {
    const cur = readFileSync(a.abs, "utf8");
    writeFileSync(a.abs, cur.replace(a.find, a.replace));
  }
  try {
    const pkgDir = t.file.split("/").slice(0, 2).join("/");
    if (DIST_PACKAGES.has(pkgDir) && pkgDir !== t.pkg) run("npx", ["tsc", "-b"], pkgDir);
    const passed = run("npx", ["vitest", "run", t.test], t.pkg);
    if (passed) {
      console.error(`GREEN  ${t.name}: ${t.pkg}/${t.test} still passes with the fix removed`);
      failures++;
    } else {
      console.log(`red    ${t.name}`);
    }
  } finally {
    for (const a of [...extra].reverse()) writeFileSync(a.abs, a.original);
    writeFileSync(abs, original);
    const pkgDir = t.file.split("/").slice(0, 2).join("/");
    if (DIST_PACKAGES.has(pkgDir) && pkgDir !== t.pkg) run("npx", ["tsc", "-b"], pkgDir);
  }
}
if (failures > 0) {
  console.error(`${failures} tamper(s) did not turn their test red`);
  process.exit(1);
}
console.log(`all ${TAMPERS.length} tampers turned their test red`);
